version: '3.1'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'pgsuperuser'
      POSTGRES_PASSWORD: 'pgsuperuserpass'
      POSTGRES_DB: 'authz'
    ports:
      - '5432:5432'