apiVersion: apps/v1
kind: Deployment
metadata:
  name: craftonomy-authz-db-deployment
  labels:
    app: authz-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authz-db
  template:
    metadata:
      labels:
        app: authz-db
    spec:
      containers:
        - name: authz-db
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: authz-db-port
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: authz-db-configmap
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: authz-db-configmap
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: authz-db-configmap
                  key: POSTGRES_DB
